---
meta:
  default:
    redis_tags:
      - blacksmith
      - dedicated
      - redis

    redis_plans:
      standalone:
        name: standalone
        description: A dedicated Redis server, with no redundancy or replication
        limit: 7
        type: standalone
        vm_type: default

releases:
  - name:    redis-forge
    version: 0.4.0
    url:     https://github.com/blacksmith-community/redis-forge-boshrelease/releases/download/v0.4.0/redis-forge-0.4.0.tgz
    sha1:    c06e2cc7a4561cc4c4dab37495ae274bad738b0b

params:
  releases:
    - (( append ))
    - (( grab releases.redis-forge ))

instance_groups:
  - name: blacksmith
    jobs:
      - release: redis-forge
        name:    redis-blacksmith-plans
        properties:
          plans: (( grab params.redis_plans || meta.default.redis_plans ))
          service:
            id:          (( grab params.redis_service_id          || "redis" ))
            name:        (( grab params.redis_service_name        || params.redis_service_id || "redis" ))
            description: (( grab params.redis_service_description || "A dedicated Redis instance, deployed on-demand" ))
            tags:        (( grab params.redis_service_tags        || meta.default.redis_tags ))
            limit:       (( grab params.redis_service_limit       || 0 ))
